# Generated by Django 3.2.3 on 2021-08-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_question2_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.standard')),
            ],
        ),
    ]
