# Generated by Django 3.1 on 2021-08-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210815_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='desc',
            field=models.CharField(default='NOT Available', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='problemNo',
            field=models.CharField(default='NOT Available', max_length=20),
        ),
    ]
